### PR TITLE
Skip duplicated [rebased pr #5]

### PR DESCRIPTION
**Pull request by Stivens73**
Please test and push to master.

### CODE REVIEW

**Comment by Stivens73** [comment]
Squashed all commits into one

**Comment by angeloc** [comment]
@Stivens73 Would you mind to add a test case for this? I think it's pretty important case to have

**Comment by manpreet-compro** [comment]
Hi @angeloc , is this PR open because of absence of test case? We are also looking for the same feature, I can try to add the test case if that is the thing we are waiting for

**Comment by angeloc** [comment]
@manpreet-compro Exactly. If you can add it, it would b perfect!

**Comment by vikas-nautiyal** [comment]
Hi @angeloc, I've added the test case for the "avoid duplicate" feature as per the conversation above. Pls check and review PR #24.
cc @manpreet-compro

**Pull request closed without merging**
